language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

script: coverage run puppy/test_puppy.py
before_install:
  pip install codecov coverage
after_success:
  codecov --token=
